# Generated by Django 3.2.6 on 2021-08-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.FileField(max_length=255, upload_to='')),
                ('success', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('analysis_class', models.IntegerField(null=True)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('request_timestamp', models.PositiveIntegerField()),
                ('response_timestamp', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ai_analysis_logs',
            },
        ),
    ]
